general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on && paplay /usr/share/sounds/freedesktop/stereo/service-login.oga
}

# ──────────────────────────────────────────────────────────────
# 1️⃣ Dim screen
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 20 # && \
    #paplay /usr/share/sounds/freedesktop/stereo/bell.oga && \
    #            notify-send "Screen dimmed"
   on-resume = brightnessctl -r # && \
    #           paplay /usr/share/sounds/freedesktop/stereo/service-login.oga
}

# ──────────────────────────────────────────────────────────────
# 2️⃣ Lock screen
listener {
    timeout = 600
    on-timeout = ${lock_cmd} && \
                 paplay /usr/share/sounds/freedesktop/stereo/service-logout.oga
}

# ──────────────────────────────────────────────────────────────
# 3️⃣ Turn off display
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off 
    #           paplay /usr/share/sounds/freedesktop/stereo/complete.oga
    on-resume = hyprctl dispatch dpms on# && sleep 0.3 && brightnessctl -r && \
    #               paplay /usr/share/sounds/freedesktop/stereo/service-login.oga
}

# ──────────────────────────────────────────────────────────────
# 4️⃣ Suspend system
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}

