
exec-once = waybar & hyprpaper
exec-once = hypridle &
exec-once = bash -lc 'sleep 1 && setsid cliphist store </dev/null >/dev/null 2>&1'
exec-once = ~/.config/hypr/env/export-env.sh
# Make Hyprland aware of local binaries and shell environment
exec-once = export PATH="$HOME/.local/bin:$PATH"
exec-once = hyprpaper
#exec-once = ghostty

exec-once = walker --gapplication-service
exec-once = elephant

# ~/.config/hypr/hyprland.conf
exec-once = env XDG_CURRENT_DESKTOP=wlroots XDG_SESSION_TYPE=wayland SWAYOSD_SCALE=1.8 SWAYOSD_TIMEOUT=2000 SWAYOSD_POSITION=center swayosd-server &
exec-once = python3 ~/.local/bin/lockkey-osd.py &

